"""
BuildemUp† — Component 3a Detection logic (Session 2).

Per SPEC v0.2.1 Section 2.2 — detects 10 extreme cases from a
DesignGapAnalysis (from C2) plus the original Brief (from C1).

Returns ExtremeCase objects with PLACEHOLDER options. S3
(option_generator.py) replaces placeholder options with real
ResolutionOption instances.

Detection sources:
  EC-001, EC-002, EC-006:    Computed from brief + envelope math
  EC-003, EC-004, EC-005,
  EC-007, EC-010:            Driven by C2 CheckResults
  EC-008, EC-009:            Hybrid (computed from CheckResult data)

†= placeholder name marker.
"""
from __future__ import annotations
from typing import Optional

from buildemup.domain.brief import Brief
from buildemup.domain.feasibility import (
    DesignGapAnalysis, FeasibilityReport, CheckResult, CheckSeverity,
)
from buildemup.domain.extreme_case import (
    ExtremeCase, ExtremeCaseId, ExtremeCaseCategory, ResolutionOption,
    ResolutionProbability,
)
from buildemup.domain.floor_requirement import (
    NBC_MINIMUM_ROOM_SIZES_SQM, RoomType,
)


# ──────────────────────────────────────────────────────────────────────
# Constants and mappings
# ──────────────────────────────────────────────────────────────────────

CIRCULATION_FACTOR = 1.35  # B-004 (S54 fix)

# B-004 (S54 May 2026): aligned with C2's hard_physics_checks.py and
# C1's room_minimums.json "typical" value (also 1.35). Prior 1.30 came
# from an outdated SPEC EC-001 reference and produced inconsistent
# detection thresholds vs C2's envelope check. Single source of truth
# is now IS 3861-2002-derived "typical residential" 1.35 across
# C1 / C2 / C3a. (Note: kb_rules/room_minimums.json also exposes
# 1.40 for small homes and 1.30 for large — full per-size sourcing
# is a future v1.x backlog item.)

# EC-002 plot width tiers
EC_002_PHYSICAL_TIER_FT = {  # < this width → HARD_FAIL handled upstream
    "any": 12,
    "2bhk": 14,
    "3bhk": 16,
}
EC_002_SEVERE_TIER_RANGES_FT = {  # detector fires EC-002 in these ranges
    "2bhk": (14, 15),
    "3bhk": (16, 18),
}
EC_002_COMFORTABLE_TIER_M = {  # >= this width → no EC, soft note in layout
    "2bhk": 5.5,  # Neufert
    "3bhk": 6.7,
}

# EC-010 vs EC-004/005/007 dedup
EC_004_005_007_CHECK_IDS = frozenset({
    "far_compliance",
    "ground_coverage_compliance",
    "stilt_mandate_compliance",
})

EC_010_CHECK_IDS = frozenset({
    "fire_tender_access",
    "electric_line_clearance",
    "water_course_clearance",
})

EC_010_FIXED_PROBABILITY = {
    "fire_tender_access": ResolutionProbability.MEDIUM,
    "water_course_clearance": ResolutionProbability.LOW,
}

# EC budget ratios
EC_008_HARD_RATIO = 1.5
EC_009_BUDGET_BUFFER_RATIO = 1.2

# Unit conversions
SQM_TO_SQFT = 10.7639
M_TO_FT = 3.28084


# ──────────────────────────────────────────────────────────────────────
# Placeholder options (S3 will replace these)
# ──────────────────────────────────────────────────────────────────────

def _make_placeholder_options() -> tuple[ResolutionOption, ...]:
    """Two placeholder options to satisfy ExtremeCase.__post_init__'s
    >=2 options invariant. S3's option_generator.py replaces these
    with real ResolutionOption instances tailored per EC.

    DO NOT TEST OPTION CONTENT IN S2 — only test case detection.
    """
    placeholder = ResolutionOption(
        option_id="PLACEHOLDER_S3_FILLS_IN",
        description="(option set will be generated by S3)",
        impact_summary="(impact will be computed by S3)",
        cost_impact=None,
        space_impact_sqft=0,
        recommended=False,
        recommendation_reason=None,
        requires_brief_change=(),
        requires_action=None,
        risk_advisory=None,
        is_preview_mode=False,
    )
    # ExtremeCase.__post_init__ doesn't enforce option_id uniqueness,
    # so two identical placeholders are fine. ExtremeDecision later
    # will need distinct option_ids — S3's responsibility.
    return (placeholder, placeholder)


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────

def _compute_min_buildable_per_floor_sqm(brief: Brief) -> float:
    """Sum of NBC-minimum room areas × circulation factor 1.35,
    divided across the floors the brief allocates.

    Used by EC-001 (against NBC envelope) and EC-006 (against
    user-stated envelope).
    """
    if not brief.floors:
        return 0.0

    total_room_area_sqm = 0.0
    for floor in brief.floors:
        for room_req in floor.rooms:
            nbc_min = NBC_MINIMUM_ROOM_SIZES_SQM[room_req.room_type]
            total_room_area_sqm += room_req.count * nbc_min

    total_with_circulation = total_room_area_sqm * CIRCULATION_FACTOR
    return total_with_circulation / len(brief.floors)


def _compute_envelope_area_sqm(brief: Brief, use_nbc_setbacks: bool) -> float:
    """Compute buildable envelope area for a brief.

    use_nbc_setbacks=True → use NBC-compliant setbacks (for EC-001)
    use_nbc_setbacks=False → use user-stated setbacks (for EC-006)
    """
    plot = brief.plot
    setbacks = (brief.nbc_compliant_setbacks
                if use_nbc_setbacks
                else brief.user_stated_setbacks)
    env_w = max(0.0, plot.width_m
                - setbacks.side_left_m - setbacks.side_right_m)
    env_d = max(0.0, plot.depth_m
                - setbacks.front_m - setbacks.rear_m)
    return env_w * env_d


def _find_check_in_blocking(
    report: FeasibilityReport, check_id: str
) -> Optional[CheckResult]:
    """Return the CheckResult with this check_id from blocking_issues,
    or None if not found.
    """
    for cr in report.blocking_issues:
        if cr.check_id == check_id:
            return cr
    return None


def _classify_electric_line(check_result: CheckResult) -> ResolutionProbability:
    """Determine HT vs LT from the check's details dict for EC-010.

    Default to MEDIUM if details don't specify line_type.
    Logged as v0.2-backlog item (add line_type field consistently).
    """
    line_type = str(check_result.details.get("line_type", "")).upper()
    if "HT" in line_type or "HIGH" in line_type:
        return ResolutionProbability.LOW
    return ResolutionProbability.MEDIUM


def _bhk_count(brief: Brief) -> int:
    """Count total bedrooms (master + regular) across all floors.
    Used by EC-002 to determine BHK-specific width tiers.
    """
    count = 0
    for floor in brief.floors:
        for room_req in floor.rooms:
            if room_req.room_type in (RoomType.BEDROOM_MASTER,
                                       RoomType.BEDROOM_REGULAR):
                count += room_req.count
    return count


# ──────────────────────────────────────────────────────────────────────
# Detection functions — one per EC
# ──────────────────────────────────────────────────────────────────────

def _detect_ec001(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-001: TOTAL_AREA_EXCEEDS_ENVELOPE (SPATIAL)

    Detection: sum(room_minimums) × 1.30 > envelope × floors
    Uses NBC-compliant setbacks envelope.
    """
    min_buildable_per_floor = _compute_min_buildable_per_floor_sqm(brief)
    nbc_envelope_per_floor = _compute_envelope_area_sqm(
        brief, use_nbc_setbacks=True
    )

    if min_buildable_per_floor <= nbc_envelope_per_floor:
        return None

    # Convert to sqft for user message
    available_sqft = nbc_envelope_per_floor * SQM_TO_SQFT
    required_sqft = min_buildable_per_floor * SQM_TO_SQFT
    floors = len(brief.floors)
    total_buildable_sqft = available_sqft * floors
    total_required_sqft = required_sqft * floors
    shortfall_sqft = total_required_sqft - total_buildable_sqft

    # Trace back to C2's envelope_sufficiency CheckResult if HARD_FAIL'd
    related_check = _find_check_in_blocking(
        gap_analysis.practical_report, "envelope_sufficiency"
    )
    blocking_gap_ids = (("envelope_sufficiency",) if related_check else ())

    user_facing_message = (
        f"Your plot fits about {available_sqft:.0f} sqft per floor "
        f"across {floors} floors = {total_buildable_sqft:.0f} sqft total. "
        f"The rooms in your brief need at least {total_required_sqft:.0f} "
        f"sqft. You're short by about {shortfall_sqft:.0f} sqft."
    )

    framing_line = (
        "Your plot doesn't have enough buildable area for everything in "
        "your brief. One of these trade-offs is necessary to make it work."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_001_TOTAL_AREA_EXCEEDS_ENVELOPE,
        category=ExtremeCaseCategory.SPATIAL,
        blocking_gap_ids=blocking_gap_ids,
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec002(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-002: PLOT_WIDTH_INSUFFICIENT (SITE)

    Three-tier detection:
      Physical (< 12/14/16 ft): HARD_FAIL handled upstream → return None
      Severe (14-15 ft 2BHK / 16-18 ft 3BHK): EC-002 fires
      Comfortable (>= 5.5m 2BHK / 6.7m 3BHK): no EC → return None
    """
    plot_width_m = brief.plot.width_m
    plot_width_ft = plot_width_m * M_TO_FT
    bhk = _bhk_count(brief)

    if bhk == 0:
        return None  # No bedrooms — width tiers don't apply

    # Determine tier thresholds based on BHK
    if bhk <= 2:
        physical_threshold_ft = EC_002_PHYSICAL_TIER_FT["2bhk"]
        comfortable_threshold_m = EC_002_COMFORTABLE_TIER_M["2bhk"]
    else:  # 3+ BHK
        physical_threshold_ft = EC_002_PHYSICAL_TIER_FT["3bhk"]
        comfortable_threshold_m = EC_002_COMFORTABLE_TIER_M["3bhk"]

    # Tier 1 — Physical: HARD_FAIL handled upstream
    if plot_width_ft < physical_threshold_ft:
        return None

    # Tier 3 — Comfortable: no EC
    if plot_width_m >= comfortable_threshold_m:
        return None

    # Tier 2 — Severe range: detector fires
    estimated_bedroom_width_ft = plot_width_ft - 4  # accounts for typical setbacks + walls

    user_facing_message = (
        f"Your plot is {plot_width_ft:.1f} ft wide. A {bhk}BHK home is "
        f"buildable here, but bedrooms will be narrow "
        f"(about {estimated_bedroom_width_ft:.1f} ft) and furniture "
        f"choices will be constrained (no king beds, wardrobes shallower "
        f"than standard, single-loaded corridor only)."
    )

    framing_line = (
        "Plots this width work, but the layout has real compromises. "
        "We want you to know what you're choosing."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_002_PLOT_WIDTH_INSUFFICIENT,
        category=ExtremeCaseCategory.SITE,
        blocking_gap_ids=(),  # Purely computed; no C2 check
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec003(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-003: NO_PARKING_POSITION (SITE)

    Detection: parking_width_feasibility CheckResult HARD_FAIL.
    """
    cr = _find_check_in_blocking(
        gap_analysis.practical_report, "parking_width_feasibility"
    )
    if cr is None:
        return None

    plot_width_ft = brief.plot.width_m * M_TO_FT
    setback_ft = (brief.user_stated_setbacks.side_left_m
                  + brief.user_stated_setbacks.side_right_m) * M_TO_FT / 2
    # ^ average side setback in feet for messaging

    user_facing_message = (
        f"Your plot is {plot_width_ft:.1f} ft wide with about "
        f"{setback_ft:.1f} ft side setbacks each. After leaving room for "
        f"the entry path, there's no way to fit a covered car bay "
        f"(needs at least 2.5m × 5m)."
    )

    framing_line = (
        "There's no place on your plot for a covered car bay. "
        "To make it work, here's what we can do."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_003_NO_PARKING_POSITION,
        category=ExtremeCaseCategory.SITE,
        blocking_gap_ids=("parking_width_feasibility",),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec004(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-004: FAR_EXCEEDED (LEGAL)

    Detection: far_compliance CheckResult HARD_FAIL.
    """
    cr = _find_check_in_blocking(
        gap_analysis.practical_report, "far_compliance"
    )
    if cr is None:
        return None

    actual_far = cr.details.get("actual_far", 0)
    permitted_far = cr.details.get("city_max_far", 0)
    plot_sqm = cr.details.get("plot_area_sqm", 1)
    excess_sqft = (actual_far - permitted_far) * plot_sqm * SQM_TO_SQFT

    user_facing_message = (
        f"Your brief works out to {actual_far:.2f} FAR. "
        f"{brief.plot.city.title()} allows up to {permitted_far:.2f} FAR "
        f"for this plot type. You're over by about {excess_sqft:.0f} sqft."
    )

    framing_line = (
        "Your brief asks for more building than your city's FAR "
        "(Floor Area Ratio) rules allow. To make this approvable, "
        "you'll need to make a structural change."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_004_FAR_EXCEEDED,
        category=ExtremeCaseCategory.LEGAL,
        blocking_gap_ids=("far_compliance",),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec005(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-005: GROUND_COVERAGE_EXCEEDED (LEGAL)

    Detection: ground_coverage_compliance CheckResult HARD_FAIL.
    """
    cr = _find_check_in_blocking(
        gap_analysis.practical_report, "ground_coverage_compliance"
    )
    if cr is None:
        return None

    actual_pct = cr.details.get("actual_gc_pct", 0)
    permitted_pct = cr.details.get("city_max_gc_pct", 0)

    user_facing_message = (
        f"Your envelope covers {actual_pct:.0f}% of the plot. "
        f"{brief.plot.city.title()} allows up to {permitted_pct:.0f}%."
    )

    framing_line = (
        "Your envelope covers more of the plot than your city's rules "
        "allow. To make it approvable, you need a different envelope shape."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_005_GROUND_COVERAGE_EXCEEDED,
        category=ExtremeCaseCategory.LEGAL,
        blocking_gap_ids=("ground_coverage_compliance",),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec006(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-006: PRACTICAL_ENVELOPE_BELOW_BUILDABLE (LEGAL)

    Detection: practical envelope (user-stated setbacks) < min buildable.
    Dedup: only fires when user_stated_setbacks differ from
    nbc_compliant_setbacks (otherwise EC-001 covers the case).
    """
    user_setbacks = brief.user_stated_setbacks
    nbc_setbacks = brief.nbc_compliant_setbacks

    # Dedup check: if user setbacks == NBC setbacks, EC-001 covers it
    if (user_setbacks.front_m == nbc_setbacks.front_m and
        user_setbacks.rear_m == nbc_setbacks.rear_m and
        user_setbacks.side_left_m == nbc_setbacks.side_left_m and
        user_setbacks.side_right_m == nbc_setbacks.side_right_m):
        return None

    min_buildable_per_floor = _compute_min_buildable_per_floor_sqm(brief)
    practical_envelope_per_floor = _compute_envelope_area_sqm(
        brief, use_nbc_setbacks=False
    )

    if min_buildable_per_floor <= practical_envelope_per_floor:
        return None

    front_ft = user_setbacks.front_m * M_TO_FT
    rear_ft = user_setbacks.rear_m * M_TO_FT
    side_ft = (user_setbacks.side_left_m + user_setbacks.side_right_m) * M_TO_FT / 2
    envelope_sqft = practical_envelope_per_floor * SQM_TO_SQFT
    min_buildable_sqft = min_buildable_per_floor * SQM_TO_SQFT

    user_facing_message = (
        f"With your stated setbacks ({front_ft:.1f}/{rear_ft:.1f}/"
        f"{side_ft:.1f} ft), your buildable envelope shrinks to "
        f"{envelope_sqft:.0f} sqft. That's below the minimum needed for "
        f"any version of your brief ({min_buildable_sqft:.0f} sqft)."
    )

    framing_line = (
        "Even with the setbacks you specified, your plot doesn't have "
        "enough envelope for the smallest version of your brief."
    )

    related_check = _find_check_in_blocking(
        gap_analysis.practical_report, "envelope_sufficiency"
    )
    blocking_gap_ids = (("envelope_sufficiency",) if related_check else ())

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_006_PRACTICAL_ENVELOPE_BELOW_BUILDABLE,
        category=ExtremeCaseCategory.LEGAL,
        blocking_gap_ids=blocking_gap_ids,
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec007(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-007: STILT_MANDATE_VIOLATED (LEGAL)

    Detection: stilt_mandate_compliance CheckResult HARD_FAIL.
    """
    cr = _find_check_in_blocking(
        gap_analysis.practical_report, "stilt_mandate_compliance"
    )
    if cr is None:
        return None

    height_m = cr.details.get("estimated_height_m", 0)
    threshold_m = cr.details.get("stilt_threshold_m", 15)

    user_facing_message = (
        f"At {height_m:.1f} m, {brief.plot.city.title()} mandates stilt "
        f"parking (rule applies above {threshold_m:.1f} m)."
    )

    framing_line = (
        "Your city requires stilt parking above a certain height. "
        "Your brief crosses that threshold."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_007_STILT_MANDATE_VIOLATED,
        category=ExtremeCaseCategory.LEGAL,
        blocking_gap_ids=("stilt_mandate_compliance",),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec008(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-008: BUDGET_CATASTROPHICALLY_LOW (BUDGET)

    Detection: cost_estimate.exact_value > budget × 1.5
    The 1.25× soft warn is C2's job (NOT detector's).

    Note: cost_estimate is a CostEstimate dataclass with field
    `exact_value` (not midpoint_inr). Read accordingly.
    """
    cost_estimate = gap_analysis.practical_report.cost_estimate
    if cost_estimate is None:
        return None

    estimate_inr = getattr(cost_estimate, "exact_value", None)
    if estimate_inr is None:
        return None

    budget_inr = brief.budget_range.max_rupees
    if budget_inr <= 0:
        return None

    if estimate_inr <= budget_inr * EC_008_HARD_RATIO:
        return None  # No EC-008 — 1.25× is C2's concern

    estimate_l = estimate_inr / 100_000
    budget_l = budget_inr / 100_000
    gap_l = estimate_l - budget_l
    gap_pct = (gap_l / budget_l) * 100

    user_facing_message = (
        f"Building this brief in {brief.plot.city.title()} costs about "
        f"₹{estimate_l:.0f} L. Your budget is ₹{budget_l:.0f} L. "
        f"The gap is ₹{gap_l:.0f} L (~{gap_pct:.0f}%). For context: "
        f"phased construction in India typically absorbs gaps up to "
        f"~30-40%; yours is beyond that."
    )

    framing_line = (
        "The gap between your budget and the cost of this brief is too "
        "large for normal solutions like phased construction or top-up "
        "loans. You'll need a fundamental decision."
    )

    related_check = _find_check_in_blocking(
        gap_analysis.practical_report, "budget_feasibility"
    )
    blocking_gap_ids = (("budget_feasibility",) if related_check else ())

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_008_BUDGET_CATASTROPHICALLY_LOW,
        category=ExtremeCaseCategory.BUDGET,
        blocking_gap_ids=blocking_gap_ids,
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec009(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-009: SOIL_REQUIRES_PILE_BUDGET_LOW (SITE+BUDGET intersect)

    Detection: soil.requires_pile == True AND
               (c7_estimate + pile_cost) > budget × 1.2

    Reads soil from C2's soil_type or soil_type_practical CheckResult
    (in either blocking_issues or soft_warnings).
    Reads pile cost from CheckResult.details if available.
    """
    # Look for soil indication in blocking_issues OR soft_warnings
    soil_check = None
    for cr in (gap_analysis.practical_report.blocking_issues
               + gap_analysis.practical_report.soft_warnings):
        if cr.check_id in ("soil_type", "soil_type_practical"):
            soil_check = cr
            break

    if soil_check is None:
        return None

    requires_pile = soil_check.details.get("requires_pile", False)
    if not requires_pile:
        return None

    cost_estimate = gap_analysis.practical_report.cost_estimate
    if cost_estimate is None:
        return None

    base_estimate_inr = getattr(cost_estimate, "exact_value", None)
    if base_estimate_inr is None:
        return None

    pile_cost_inr = soil_check.details.get("pile_cost_inr", 500_000)  # default ₹5L
    total_inr = base_estimate_inr + pile_cost_inr
    budget_inr = brief.budget_range.max_rupees

    if total_inr <= budget_inr * EC_009_BUDGET_BUFFER_RATIO:
        return None

    soil_class = soil_check.details.get("soil_class", "soft soil")
    base_l = base_estimate_inr / 100_000
    pile_l = pile_cost_inr / 100_000
    total_l = total_inr / 100_000
    budget_l = budget_inr / 100_000

    user_facing_message = (
        f"Your site has {soil_class} soil. That requires pile foundation "
        f"(about ₹{pile_l:.0f} L extra). Combined with your build "
        f"estimate of ₹{base_l:.0f} L, you'd need ₹{total_l:.0f} L. "
        f"Your budget is ₹{budget_l:.0f} L."
    )

    framing_line = (
        "Your soil needs a pile foundation, which adds significant cost. "
        "Combined with your build estimate, that exceeds your budget."
    )

    blocking_gap_ids = []
    if soil_check.severity == CheckSeverity.HARD_FAIL:
        blocking_gap_ids.append(soil_check.check_id)
    budget_check = _find_check_in_blocking(
        gap_analysis.practical_report, "budget_feasibility"
    )
    if budget_check:
        blocking_gap_ids.append("budget_feasibility")

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_009_SOIL_REQUIRES_PILE_BUDGET_LOW,
        category=ExtremeCaseCategory.SITE,  # SITE+BUDGET intersect; SITE is primary
        blocking_gap_ids=tuple(blocking_gap_ids),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=ResolutionProbability.NOT_APPLICABLE,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


def _detect_ec010(
    gap_analysis: DesignGapAnalysis, brief: Brief
) -> Optional[ExtremeCase]:
    """EC-010: APPROVAL_BLOCKER_UNREMEDIABLE (APPROVAL)

    Detection: any blocking CheckResult with check_id in EC_010_CHECK_IDS.
    Dedup: EC-004/005/007 cover their own check_ids; this only fires for
    fire/electric/watercourse blockers.

    Per-blocker resolution_probability:
      fire_tender_access → MEDIUM
      electric_line_clearance → MEDIUM (LT default) or LOW (HT)
      water_course_clearance → LOW
    """
    matching = [
        cr for cr in gap_analysis.practical_report.blocking_issues
        if cr.check_id in EC_010_CHECK_IDS
    ]
    if not matching:
        return None

    # If multiple, surface the highest-impact one (LOW resolution_probability first)
    def _probability_rank(cr: CheckResult) -> int:
        """Lower rank = higher severity for surfacing order."""
        if cr.check_id == "electric_line_clearance":
            prob = _classify_electric_line(cr)
        else:
            prob = EC_010_FIXED_PROBABILITY.get(
                cr.check_id, ResolutionProbability.MEDIUM
            )
        return {
            ResolutionProbability.LOW: 0,
            ResolutionProbability.MEDIUM: 1,
            ResolutionProbability.HIGH: 2,
        }.get(prob, 3)

    matching.sort(key=_probability_rank)
    primary = matching[0]

    # Determine resolution_probability for the primary check
    if primary.check_id == "electric_line_clearance":
        resolution_prob = _classify_electric_line(primary)
    else:
        resolution_prob = EC_010_FIXED_PROBABILITY.get(
            primary.check_id, ResolutionProbability.MEDIUM
        )

    # Build framing line per resolution_probability
    if resolution_prob == ResolutionProbability.LOW:
        framing_line = (
            "This kind of approval blocker is rarely resolvable on this "
            "plot. Most often, the realistic path is a different plot."
        )
        prob_explainer = "rarely resolvable through variance applications"
    else:  # MEDIUM (HIGH not used for these subtypes)
        framing_line = (
            "This kind of approval blocker often has a resolution path. "
            "Here's what we can try."
        )
        prob_explainer = (
            "often resolvable through minor design adjustments or "
            "local consultation"
        )

    blocker_description = primary.message[:200]  # truncate

    user_facing_message = (
        f"This site has an approval blocker: {blocker_description}. "
        f"This is {prob_explainer}. Without resolving this, the building "
        f"won't be approved."
    )

    return ExtremeCase(
        case_id=ExtremeCaseId.EC_010_APPROVAL_BLOCKER,
        category=ExtremeCaseCategory.APPROVAL,
        blocking_gap_ids=(primary.check_id,),
        user_facing_message=user_facing_message,
        framing_line=framing_line,
        resolution_probability=resolution_prob,
        options=_make_placeholder_options(),
        detected_at_iteration=0,
    )


# ──────────────────────────────────────────────────────────────────────
# Public API: ExtremeCaseDetector
# ──────────────────────────────────────────────────────────────────────

class ExtremeCaseDetector:
    """Detects all extreme cases in a DesignGapAnalysis.

    Public API:
        detect(gap_analysis, brief) -> tuple[ExtremeCase, ...]

    Returns ExtremeCase objects with placeholder options. S3
    (option_generator.py) replaces placeholders with real options.

    Order of returned cases: detection order (EC-001 through EC-010).
    Orchestrator (S6) handles priority sorting.
    """

    @staticmethod
    def detect(
        gap_analysis: DesignGapAnalysis,
        brief: Brief,
    ) -> tuple[ExtremeCase, ...]:
        """Detect all extreme cases in the gap analysis.

        Returns a tuple of ExtremeCase. Empty tuple if no blockers
        of EC-recognized type. Order is detection order, NOT priority
        order — orchestrator (S6) handles priority sorting.
        """
        detectors = [
            _detect_ec001, _detect_ec002, _detect_ec003,
            _detect_ec004, _detect_ec005, _detect_ec006,
            _detect_ec007, _detect_ec008, _detect_ec009,
            _detect_ec010,
        ]
        cases = [d(gap_analysis, brief) for d in detectors]
        return tuple(c for c in cases if c is not None)
